steps:
  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/gmail-scanner-347019/gmail-scanner/app:latest', '.' ]
  - name: gcr.io/cloud-builders/docker
    args: [ 'push', 'europe-west1-docker.pkg.dev/gmail-scanner-347019/gmail-scanner/app:latest' ]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - gcloud
      - run
      - deploy
      - gmail-scanner
      - --image=europe-west1-docker.pkg.dev/gmail-scanner-347019/gmail-scanner/app:latest
      - --region=europe-west1
      - --platform=managed