server:
  port: ${PORT:8080}
  forward-headers-strategy: framework
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/gmail.readonly
logging:
  level:
    com.gmail.scanner: DEBUG

app:
  name: GmailScanner
  start-year: 2020
  gmail:
    batch-size: 20
    page-max-results: 500 # Gmail API maximum